services:
  api:
    platform: linux/amd64
    image: us-west1-docker.pkg.dev/website-346705/website/api:latest
    build:
      context: ./api
    environment:
      PORT: "9090"
    ports:
      - "9090:9090"
    volumes:
      - ./api/index.js:/usr/src/app/index.js
      - ./api/package.json:/usr/src/app/package.json
      - ./api/package-lock.json:/usr/src/app/package-lock.json

  web:
    image: web
    build:
      context: ./web
    volumes:
      - ~/.cache/firebase/emulators/:/root/.cache/firebase/emulators
      - ./web/public:/usr/src/app/public
      - ./web/.firebase:/usr/src/app/.firebase
      - ./web/firebase.json:/usr/src/app/firebase.json
      - ./web/firestore.indexes.json:/usr/src/app/firestore.indexes.json
      - ./web/firestore.rules:/usr/src/app/firestore.rules
      - ./web/storage.rules:/usr/src/app/storage.rules
      - ./web/package.json:/usr/src/app/package.json
      - ./web/package-lock.json:/usr/src/app/package-lock.json
    environment:
      FIREBASE_TOKEN: "${FIREBASE_TOKEN}"
    ports:
      - "4000:4000"
      - "5555:5555"
      - "8080:8080"
      - "9199:9199"

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
