services:
  api:
    image: gcr.io/website-346705/api
    build:
      context: ./api
      dockerfile: ../Dockerfile.api
    environment:
      PORT: "9090"
    volumes:
      - ./api/index.js:/usr/src/app/index.js
      - ./api/package.json:/usr/src/app/package.json
      - ./api/package-lock.json:/usr/src/app/package-lock.json
    networks:
      - default

  web:
    image: gcr.io/website-346705/web
    build:
      context: ./web
      dockerfile: ../Dockerfile.web
    volumes:
      - ~/.cache/firebase/emulators/:/root/.cache/firebase/emulators
      - ./web/public:/usr/src/app/public
      - ./web/.firebase:/usr/src/app/.firebase
      - ./web/firebase.json:/usr/src/app/firebase.json
      - ./web/firestore.indexes.json:/usr/src/app/firestore.indexes.json
      - ./web/firestore.rules:/usr/src/app/firestore.rules
      - ./web/storage.rules:/usr/src/app/storage.rules
      - ./web/package.json:/usr/src/app/package.json
      - ./web/package-lock.json:/usr/src/app/package-lock.json
    environment:
      FIREBASE_TOKEN: "${FIREBASE_TOKEN}"
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
      - "9199:9199"
    networks:
      - default

  proxy:
    image: gcr.io/website-346705/proxy
    build:
      context: ./proxy
      dockerfile: ../Dockerfile.proxy
    environment:
      PROXY_PORT: "80"
      WEB_PORT: "5000"
      API_PORT: "9090"
    ports:
      - "80:80"
    volumes:
      - ./proxy/proxy_server.js:/usr/src/app/proxy_server.js
      - ./proxy/package.json:/usr/src/app/package.json
      - ./proxy/package-lock.json:/usr/src/app/package-lock.json
    networks:
      - default
