name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/538423338346/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-action-479701882@website-346705.iam.gserviceaccount.com'
      - id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'website'
          image: 'gcr.io/website-346705/api'
