name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  publish_to_firebase_hosting:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBSITE_346705 }}'
          channelId: live
          projectId: website-346705
          entryPoint: src/web
