name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/538423338346/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-action-479701882@website-346705.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: 'Use gcloud CLI'
        run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'

      - name: Build and Push Container
        run: |-
          make build-api
          make push-api

      - name: Deploy website API to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'website'
          image: 'us-west1-docker.pkg.dev/website-346705/website/api:latest'
